---
title: "R SQL Data Manipulation"
author: "Lavinia Carabet"
output: 
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, message=FALSE, warning =FALSE}
#install.packages(c("dplyr", "dbplyr", "RSQLite", "stringr", "purrr"))
```

### Load libraries

```{r, message=FALSE, warning =FALSE}
library(dplyr)
library(dbplyr)
library(RSQLite)
library(stringr)
library(purrr)
```

### Connect to database

```{r}
cuff_data.db <- DBI::dbConnect(RSQLite::SQLite(), './cuffData.db')
```

### List database tables
```{r}
dplyr::tbl(cuff_data.db, sql("SELECT name FROM sqlite_master WHERE type='table'")) 
```
```{r}
RSQLite::dbListTables(cuff_data.db) 
```
### Querying the database

With SQL syntax

```{r}
tbl(cuff_data.db, sql("SELECT * FROM genes LIMIT 10"))
```

With dplyr syntax

```{r}
genes <- tbl(cuff_data.db, "genes") 

genes %>%
  select(gene_id, gene_short_name, locus) %>%
  head(10)

show_query(head(genes, 10))
```

```{r}
genes %>%
  filter(substr(locus,1,4) == "chr1") %>%
  select(gene_id, gene_short_name, locus)  %>%
  head(10)
  
genes %>%
  filter(substr(locus,1,4) == "chr1") %>%
  select(gene_id, gene_short_name, locus) %>%
  show_query()
```

```{r}
genes %>%
  collect() %>%
  group_by(substr(locus,1,str_locate(locus, ":"))) %>%
  tally() 
```

```{r}
genes %>%
  collect() %>%
  filter(str_starts(locus, "chr1:")) %>%
  tally()
```

```{r}
genes %>%
  collect() %>%
  tally() 
```

```{r}
genes %>%
  summarize(
    n=n_distinct(gene_id)
    )

genes %>%
  summarize(
    n=n_distinct(gene_id)
    ) %>% 
  show_query()
```


```{r}
geneExpDiffData <- tbl(cuff_data.db, "geneExpDiffData")
head(geneExpDiffData, 10)

geneExpDiffData %>%
  collect() %>%
  tally() 
```


```{r}
geneData <- tbl(cuff_data.db, "geneData")
head(geneData, 10)

geneData %>%
  collect() %>%
  tally() 
```

### Joins

With dplyr
```{r}
genes %>%
  inner_join(geneExpDiffData, by="gene_id") %>%
  select(-c(class_code, nearest_ref_id, length, coverage)) %>%
  filter(status == "OK" & significant == "yes") %>%
  head(10)

genes %>%
  inner_join(geneExpDiffData, by="gene_id") %>%
  select(-c(class_code, nearest_ref_id, length, coverage)) %>%
  filter(status == "OK" & significant == "yes") %>%
  show_query()

genes %>%
  inner_join(geneExpDiffData, by="gene_id") %>%
  select(-c(class_code, nearest_ref_id, length, coverage)) %>%
  filter(status == "OK" & significant == "yes") %>%
  tally()
```

With purrr
```{r}
library(purrr)

diffExp <- reduce(
  list(genes, geneExpDiffData),
  right_join) %>%
  select(-c(class_code, nearest_ref_id, length, coverage)) %>%
  filter(status == "OK" & significant == "yes") 

diffExp %>% head(10)

diffExp %>% tally()
```
```{r}
library(purrr)

diffExp <- reduce(
  list(genes, geneExpDiffData),
  right_join) %>%
  select(-c(class_code, nearest_ref_id, length, coverage)) %>%
  filter(status == "OK" & significant == "yes" & !is.na(test_stat)) %>%
  arrange(log2_fold_change, q_value)

diffExp <- reduce(
  list(genes, geneExpDiffData),
  right_join) %>%
  select(-c(class_code, nearest_ref_id, length, coverage)) %>%
  filter(status == "OK" & significant == "yes" & !is.na(test_stat)) %>%
  arrange(log2_fold_change, q_value) %>%
  show_query()

diffExp %>% head(10)

diffExp %>% tally()
```

